# Generated by Django 6.0.3 on 2026-03-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch that primarily uses this classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='Academic.batch'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='discipline',
            field=models.ForeignKey(blank=True, help_text='Department/Discipline that primarily uses this classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='Academic.discipline'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section that primarily uses this classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='Academic.section'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester that primarily uses this classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='Academic.semester'),
        ),
    ]
