# Generated by Django 6.0.3 on 2026-03-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('timetables', '0002_classroom_batch_classroom_discipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_code', models.CharField(help_text='e.g., LAB-101, CS-LAB-1', max_length=20, unique=True)),
                ('lab_name', models.CharField(help_text='e.g., Computer Science Lab 1', max_length=100)),
                ('building', models.CharField(default='Main Building', max_length=100)),
                ('floor', models.CharField(blank=True, help_text='e.g., Ground Floor, 1st Floor', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Number of students that can sit')),
                ('computer_count', models.PositiveIntegerField(default=0, help_text='Number of computers')),
                ('computer_config', models.TextField(blank=True, help_text='e.g., Intel i5, 8GB RAM, 512GB SSD')),
                ('operating_system', models.CharField(blank=True, help_text='e.g., Windows 11, Ubuntu 22.04', max_length=50)),
                ('software_installed', models.TextField(blank=True, help_text='List of installed software (one per line)')),
                ('has_projector', models.BooleanField(default=False)),
                ('has_smartboard', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False, help_text='Air Conditioning')),
                ('has_generator', models.BooleanField(default=False, help_text='Generator Backup')),
                ('has_wifi', models.BooleanField(default=False, help_text='WiFi Available')),
                ('has_printer', models.BooleanField(default=False, help_text='Printer Available')),
                ('has_whiteboard', models.BooleanField(default=False, help_text='Whiteboard Available')),
                ('internet_speed', models.CharField(blank=True, help_text='e.g., 100 Mbps', max_length=50)),
                ('network_type', models.CharField(blank=True, help_text='e.g., LAN, Fiber Optic', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batches', models.ManyToManyField(blank=True, help_text='Batches that can use this lab', related_name='laboratories', to='Academic.batch')),
                ('disciplines', models.ManyToManyField(blank=True, help_text='Disciplines that can use this lab', related_name='laboratories', to='Academic.discipline')),
                ('primary_batch', models.ForeignKey(blank=True, help_text='Primary batch for this lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_laboratory', to='Academic.batch')),
                ('primary_discipline', models.ForeignKey(blank=True, help_text='Primary discipline for this lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_laboratory', to='Academic.discipline')),
                ('primary_section', models.ForeignKey(blank=True, help_text='Primary section for this lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_laboratory', to='Academic.section')),
                ('primary_semester', models.ForeignKey(blank=True, help_text='Primary semester for this lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_laboratory', to='Academic.semester')),
                ('sections', models.ManyToManyField(blank=True, help_text='Sections that can use this lab', related_name='laboratories', to='Academic.section')),
                ('semesters', models.ManyToManyField(blank=True, help_text='Semesters that can use this lab', related_name='laboratories', to='Academic.semester')),
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratories',
                'ordering': ['lab_code'],
            },
        ),
    ]
