# Generated by Django 6.0.3 on 2026-04-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_remove_user_from_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('Coordinator', 'Coordinator'), ('Section Head', 'Section Head'), ('Office Clerk', 'Office Clerk'), ('Accounts', 'Accounts Officer'), ('Librarian', 'Librarian')], default='Office Clerk', max_length=50),
        ),
    ]
