# Generated by Django 6.0.3 on 2026-04-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_adminprofile_employee_id_adminprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='assigned_disciplines',
            field=models.JSONField(blank=True, default=list, help_text='List of discipline IDs for multi-discipline roles'),
        ),
    ]
