# Generated by Django 6.0.3 on 2026-05-23 10:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0006_alter_subject_options_alter_subject_unique_together_and_more'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('mid_term', 'Mid Term'), ('final', 'Final'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('lab', 'Lab'), ('attendance', 'Attendance')], max_length=20)),
                ('exam_date', models.DateField(default=django.utils.timezone.now)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Academic.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subject.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-exam_date'],
                'unique_together': {('exam_type', 'subject', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_number', models.CharField(max_length=50, unique=True)),
                ('transcript_type', models.CharField(choices=[('official', 'Official Transcript'), ('unofficial', 'Unofficial Transcript'), ('provisional', 'Provisional Certificate')], max_length=20)),
                ('issue_date', models.DateField()),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_credits_attempted', models.PositiveIntegerField(default=0)),
                ('total_credits_earned', models.PositiveIntegerField(default=0)),
                ('total_quality_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_issued', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='student.student')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('official', 'Official Transcript'), ('unofficial', 'Unofficial Transcript'), ('provisional', 'Provisional Certificate'), ('duplicate', 'Duplicate Degree')], default='official', max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_copies', models.PositiveIntegerField(default=1)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Pickup from Office'), ('courier', 'Courier Service'), ('email', 'Email')], default='pickup', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_requests', to='student.student')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_marks', models.JSONField(default=dict, help_text='JSON object containing marks for each subject')),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_possible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cgpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('passed_subjects', models.IntegerField(default=0)),
                ('failed_subjects', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.batch')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.section')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_results', to='student.student')),
            ],
            options={
                'ordering': ['student__student_id'],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam_manag.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='student.student')),
            ],
            options={
                'ordering': ['student__student_id'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_term_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('final_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('quiz_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('assignment_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('lab_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('attendance_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2, null=True)),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('is_passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.section')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'ordering': ['subject__code'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
