# Generated by Django 6.0.3 on 2026-04-07 05:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0006_alter_subject_options_alter_subject_unique_together_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('project', 'Project'), ('lab', 'Lab Report')], default='assignment', max_length=20)),
                ('assignment_file', models.FileField(upload_to='assignments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'ppt', 'pptx'])])),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('sections', models.ManyToManyField(blank=True, related_name='assignments', to='Academic.section')),
                ('subject_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subject.subjectassign')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'zip'])])),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late Submission'), ('resubmitted', 'Resubmitted'), ('rejected', 'Rejected - Plagiarism'), ('graded', 'Graded')], default='submitted', max_length=20)),
                ('marks_obtained', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('teacher_feedback', models.TextField(blank=True)),
                ('plagiarism_score', models.FloatField(default=0)),
                ('is_plagiarized', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignm.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='student.student')),
            ],
            options={
                'ordering': ['-submitted_date'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
