# Generated by Django 6.0.3 on 2026-05-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcomit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'ordering': ['-created_at'], 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AddField(
            model_name='cases',
            name='case_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='committee_hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='committee_hearing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='committee_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='committee_venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='cases/evidence/'),
        ),
        migrations.AddField(
            model_name='cases',
            name='incident_date',
            field=models.DateField(blank=True, help_text='Date when incident occurred', null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=50),
        ),
    ]
