# Generated by Django 6.0.3 on 2026-04-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_alter_subjectassign_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='desciplain',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
    ]
